config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

    resources :articles
    root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save   
    redirect_to @article
    end 
  end
  private
    def article_params
      params.require(:article).permit(:token, :team_id, :team_domain, :channel_id, :channel_name, :user_id, :user_name, :text, :trigger_word)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<%= link_to 'New Form', new_article_path %>
<table>
  <tr>
    <th>Token</th>
    <th>Team id</th>
    <th>Team Domain</th>
    <th>Channel id</th>
    <th>Channel Name</th>
    <th>User id</th>
    <th>User Name</th>
    <th>Text</th>
    <th>Trigger Word</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.token %></td>
      <td><% article.team_id =%></td>
      <td><% article.team_domain =%></td>
      <td><% article.channel_id =%></td>
      <td><% article.channel_name =%></td>
      <td><% article.user_id =%></td>
      <td><% article.user_name =%></td>
      <td><%= article.text %></td>
      <td><%= article.trigger_word %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Form</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </p>

  <p>
    <%= f.label :team_id %><br>
    <%= f.text_field :team_id %>
  </p>

  <p>
    <%= f.label :team_domain %><br>
    <%= f.text_field :team_domain %>
  </p>

  <p>
    <%= f.label :channel_id %><br>
    <%= f.text_field :channel_id %>
  </p>

  <p>
    <%= f.label :channel_name %><br>
    <%= f.text_field :channel_name %>
  </p>

  <p>
    <%= f.label :timestamp %><br>
    <%= f.text_field :timestamp %>
  </p>

  <p>
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </p>

  <p>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.label :trigger_word %><br>
    <%= f.text_field :trigger_word %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Token:</strong>
  <%= @article.token %>
</p>
 
<p>
  <strong>Team id:</strong>
  <%= @article.team_id %>
</p>

<p>
  <strong>Team Domain:</strong>
  <%= @article.team_domain %>
</p>
 
<p>
  <strong>Channel id:</strong>
  <%= @article.channel_id %>
</p>

<p>
  <strong>Channel Name:</strong>
  <%= @article.channel_name %>
</p>
 
<p>
  <strong>User id:</strong>
  <%= @article.user_id %>
</p>

<p>
  <strong>User Name:</strong>
  <%= @article.user_name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Trigger Word:</strong>
  <%= @article.trigger_word %>
</p>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatbot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<%= link_to 'My Blog', controller: 'articles' %>